### ISSUE TITLE
CSP policy is blocking CSS, images and scripts

### ISSUE THREAD

**Issue by fmarier** [mozilla/itisatrap#19]
A new `default-src 'none'` CSP policy was added to these URLs and is preventing the pages from displaying correctly.
![its-a-tracker](https://cloud.githubusercontent.com/assets/167821/21825329/276ac72c-d738-11e6-864b-263dde9027a4.png)

**Comment by groovecoder** [comment]
Wow yeah. How is this site even deployed? Who knows?

**Comment by bensternthal** [comment]
I've done some PR reviews here in the past to help out so I have some knowledge here.

The site content is owned by fmarier, webops hosts & manages deployment.

https://mana.mozilla.org/wiki/display/websites/itisatrap.org

**Comment by fmarier** [comment]
It's auto-deployed from the GitHub repo now.

**Comment by fmarier** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1330108.

**Comment by fmarier** [comment]
Fixed.
